RUN apt-get update 
RUN apt-get install –y nginxFROM ubuntu:18.04

RUN apt install nginx 
RUN -y
COPY /app1 /var/www/html
COPY /app2 /var/www/html
COPY /Nginxfile /etc/nginx
EXPOSE 80

CMD ['nginx' , 'g' , 'daemon off']
